adding support for github presubmit tests

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -10,10 +10,6 @@ RUN apt-get update && apt-get install -y \
 RUN add-apt-repository ppa:ubuntu-toolchain-r/test && apt update
 
 RUN apt-get install -y \
-    clang \
-    clangd \
-    clang-tidy \
-    clang-format \
     libc6-dev \
     libc++-dev \
     libc++abi-dev \
@@ -23,12 +19,14 @@ RUN apt-get install -y \
     vim \
     bash \
     bash-completion \
+    entr \
+    coreutils \
     sudo
 
 RUN rm -rf /var/lib/apt/lists/*
 
-RUN wget https://apt.llvm.org/llvm.sh 
-RUN chmod +x llvm.sh 
+RUN wget https://apt.llvm.org/llvm.sh
+RUN chmod +x llvm.sh
 RUN ./llvm.sh 17
 RUN rm -f llvm.sh
 RUN apt-get update && apt-get install -y clang-tidy-17 clang-format-17  && rm -rf /var/lib/apt/lists/*
@@ -39,6 +37,8 @@ RUN update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/cl
     update-alternatives --set clang-format /usr/bin/clang-format-17
 RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-17 100 && \
     update-alternatives --set clang /usr/bin/clang-17
+RUN update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-17 100 && \
+    update-alternatives --set clang++ /usr/bin/clang++-17
 RUN update-alternatives --install /usr/bin/clang-cpp clang-cpp /usr/bin/clang-cpp-17 100 && \
     update-alternatives --set clang-cpp /usr/bin/clang-cpp-17
 RUN update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-17 100 && \
@@ -52,21 +52,40 @@ RUN wget -O /usr/local/bin/buildifier https://github.com/bazelbuild/buildtools/r
 
 # Add bazel/buildifier to PATH
 ENV PATH="/usr/local/bin:$PATH"
-
+RUN echo '#!/bin/bash\n\
+set +e\n\
+LOCKFILE="/tmp/rebuild_comp_db.lock"\n\
+if [ -e "$LOCKFILE" ] && kill -0 "$(cat "$LOCKFILE")" 2>/dev/null; then\n\
+    echo "Script is already running. Exiting."\n\
+    exit 1\n\
+fi\n\
+echo $$ > "$LOCKFILE"\n\
+trap "rm -f $LOCKFILE" EXIT\n\
+if [ ! -d "/workspaces/valkey-search" ]; then\n\
+echo "Error: Directory /workspaces/valkey-search does not exist."\n\
+exit 1\n\
+fi\n\
+cd /workspaces/valkey-search\n\
+while sleep 1; do\n\
+find src testing vmsdk/src vmsdk/testing -type f \\( -iname \\*.cc -o -iname \\*.h -o -iname BUILD \\) | entr -d bazel run @hedron_compile_commands//:refresh_all &> /dev/null\n\
+done' > /usr/local/bin/refresh_comp_db.sh && chmod +x /usr/local/bin/refresh_comp_db.sh
 # Set working directory
 WORKDIR /workspace
 
 # Add non-root user for development
 RUN useradd -m vscode && echo "vscode ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
+
 USER vscode
 
 # Add an alias for 'vi' to point to 'vim' if 'vi' doesn't exist
 RUN echo 'if ! command -v vi &> /dev/null; then alias vi="vim"; fi' >> /home/vscode/.bashrc
-
+RUN echo 'refresh_comp_db.sh &> /dev/null &' >> /home/vscode/.bashrc
 # Ensure the history file exists and configure permissions
 RUN touch  /home/vscode/.bash_history && chmod 600  /home/vscode/.bash_history
 
 ENV CC=clang
 ENV CXX=clang++
+
+
 # Default shell
 SHELL ["/bin/bash", "-c"]
